{
    # Default all-in-one configs
    'seed': 0, 
    'vit': 'vit_base_patch16_224', 
    'shared_embedding_dim': 512, 
    'hidden_size': 768, 
    'num_heads': 12, 
    'num_layers': 12, 
    'drop_rate': 0.1, 
    'image_size': 224,
    'max_text_len': 40,
    # Fixed training settings
    'val_check_interval': 1.0, 
    'optim_type': 'adamw', 
    'learning_rate': 0.00000005,
    'weight_decay': 0.5,
    'decay_power': 1, 
    'warmup_steps': 0.1, 
    'end_lr': 0,
    'lr_mult': 1,
    'num_nodes': 1,
    'num_workers': 8,
    'precision': 16,
    'fast_dev_run': False,
    # Logging
    'exp_name': 'git',
    'log_dir': 'tmp', 
    # Model settings
    'use_clip': False,
    'use_git': True,
    'num_frames': 3,
    # Training settings
    'batch_size': 64,
    'per_gpu_batchsize': 32,
    'num_gpus': 1,
    'max_epoch': 30,
    'test_only': True, 
    # Masking settings
    'masking_type': 'one_modality',
    'masking_prob': 1.0,
    # Loading models
    # 'load_path': '/dvmm-filer3a/users/kevin/all-in-one-main/pretrained/all-in-one-base.ckpt',
    'load_path': '/dvmm-filer3a/users/kevin/temporal-relations/tmp/git_2024_3_21/version_0/checkpoints/epoch=8-step=62801.ckpt',
    # 'resume_from': '/dvmm-filer3a/users/kevin/temporal-relations/result/nlp_2024_2_4/version_0/checkpoints/epoch=5-step=41867.ckpt',
    # 'resume_from': '/dvmm-filer3a/users/kevin/temporal-relations/tmp/git_2024_3_5/version_0/checkpoints/epoch=4-step=34889.ckpt',
    'resume_from': '/dvmm-filer3a/users/kevin/temporal-relations/tmp/git_2024_3_21/version_0/checkpoints/epoch=8-step=62801.ckpt',
    # 'resume_from': None
}